version: '2'

services:
  master:
    image: chrislusf/seaweedfs # use a remote image
    ports:
    - 9333:9333
    command: "master"
    # 文件映射，左边本地右边容器内
    volumes:
    - ./weedfs/master:/data
  volume1:
    image: chrislusf/seaweedfs # use a remote image
    command: 'volume -max=3 -mserver="master:9333" -port=8080'
    # 文件映射，左边本地右边容器内，多volume需要分开这个
    volumes:
    - ./weedfs/volume1:/data
    depends_on:
    - master
  volume2:
    image: chrislusf/seaweedfs # use a remote image
    command: 'volume -max=3 -mserver="master:9333" -port=8080'
    # 文件映射，左边本地右边容器内，多volume需要分开这个
    volumes:
    - ./weedfs/volume2:/data
    depends_on:
    - master
  volume3:
    image: chrislusf/seaweedfs # use a remote image
    command: 'volume -max=3 -mserver="master:9333" -port=8080'
    # 文件映射，左边本地右边容器内，多volume需要分开这个
    volumes:
    - ./weedfs/volume3:/data
    depends_on:
    - master
  filer:
    image: chrislusf/seaweedfs # use a remote image
    ports:
    - 8888:8888
    - 18888:18888
    command: 'filer -master="master:9333"'
    tty: true
    stdin_open: true
    depends_on:
    - master
    - volume1
    - volume2
    - volume3